# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  # ubuntu-24.04-arm is a valid GitHub-hosted ARM64 runner
  labels:
    - ubuntu-24.04-arm
